######################## default configuration ####################
baseURL = "https://example.com"
title = "GZFBEN"
theme = "port-hugo"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 3


#################### default parameters ################################
[params]
copyright = "Copyright Ben Guo &copy;"
# Meta data
description = "CS + AI"
author = "Ben guo"
favicon = "images/G_icon.png"
google_analytics = "G-ABCDEFG123"
logo_light = "images/G_icon.png"
logo_dark = "images/G_icon.png"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/BEN-GZF"

[[params.social]]
icon = "fab fa-linkedin"
link = "www.linkedin.com/in/zhefan-guo-4722a8224"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:zhefan.guo@uconn.edu"

contentDir = "content/english"
weight = 1
home = "Home"
